### ISSUE TITLE
when playing some videos it Redirecting to Safari

### ISSUE THREAD

**Issue by Bkishoresharma** [youtube/youtube-ios-player-helper#65]
My requirement is AutoPlay a video. For some video Id's it redirecting to safari. i struck on this issue. help me

**Comment by chiakie** [comment]
It's should be solved in current version.

**Comment by Kowaio** [comment]
Hello @Bkishoresharma 

Indeed, this bug should be solved. In the meantime, please check the link below:

http://stackoverflow.com/questions/27820123/bug-in-youtube-ios-player-helper-library

It should do the thing.

Best,

K

**Comment by Bkishoresharma** [comment]
thank you chiakle and Kowaio

**Comment by montekaka** [comment]
i still see the issue with the 0.1.1

which version should i use?

**Comment by JALsnipe** [comment]
@montekaka this appears to have been fixed in PR #58.  Can you verify you're using the latest classes in the repo and then post the URL you're having this problem with?

**Comment by montekaka** [comment]
@JALsnipe is it the fixed included in pod 'youtube-ios-player-helper', '~> 0.1.1'?

Currently, i'm using this temporary solution.
http://stackoverflow.com/questions/27820123/bug-in-youtube-ios-player-helper-library

**Comment by JALsnipe** [comment]
No, the pod is not up to date.  That's why I specifically asked you to test with the latest class files in the repo.
